export const data = [
{country: "Afghanistan", UTCoffset: "+04:30", DST: "-", DSTperiodStartEnd: ""},
{country: "Aland Islands (Finland)", UTCoffset: "+02:00", DST: "+03:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Albania", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Algeria", UTCoffset: "+01:00", DST: "-", DSTperiodStartEnd: ""},
{country: "American Samoa (USA)", UTCoffset: "-11:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Andorra", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Angola", UTCoffset: "+01:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Anguilla (UK)", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Antigua and Barbuda", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Argentina", UTCoffset: "-03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Armenia", UTCoffset: "+04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Aruba (Netherlands)", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Ascension Island (UK)", UTCoffset: "+00:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Australia, Western Australia (WA)", UTCoffset: "+08:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Australia, South Australia (SA)", UTCoffset: "+09:30", DST: "+10:30", DSTperiodStartEnd: "1-st Sunday in October, 02:00 1-st Sunday in April, 03:00"},
{country: "Australia, Northern Territory (NT)", UTCoffset: "+09:30", DST: "-", DSTperiodStartEnd: ""},
{country: "Australia, New South Wales (NSW), Tasmania (TAS), …apital Territory (ACT) with Canberra capital city", UTCoffset: "+10:00", DST: "+11:00", DSTperiodStartEnd: "1-st Sunday in October, 02:00 1-st Sunday in April, 03:00"},
{country: "Australia, Queensland (QLD)", UTCoffset: "+10:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Australia, Lord Howe Island (New South Wales)", UTCoffset: "+10:30", DST: "+11:00", DSTperiodStartEnd: "1-st Sunday in October, 02:00 1-st Sunday in April, 02:00"},
{country: "Australia, Macquarie Island (Tasmania)", UTCoffset: "+11:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Austria", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Azerbaijan", UTCoffset: "+04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Bahamas", UTCoffset: "-05:00", DST: "-04:00", DSTperiodStartEnd: "2-nd Sunday in March, 02:00 1-st Sunday in November, 02:00"},
{country: "Bahrain", UTCoffset: "+03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Bangladesh", UTCoffset: "+06:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Barbados", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Belarus", UTCoffset: "+03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Belgium", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Belize", UTCoffset: "-06:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Benin", UTCoffset: "+01:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Bermuda (UK)", UTCoffset: "-04:00", DST: "-03:00", DSTperiodStartEnd: "2-nd Sunday in March, 02:00 1-st Sunday in November, 02:00"},
{country: "Bhutan", UTCoffset: "+06:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Bolivia", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Bonaire (Netherlands)", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Bosnia and Herzegovina", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Botswana", UTCoffset: "+02:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Brazil, Acre, Southwest Amazonas", UTCoffset: "-05:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Brazil, Most of Amazonas, Rondonia, Roraima", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Brazil, Mato Grosso do Sul, Mato Grosso", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Brazil, Alagoas, Amapa, Maranhao, Para, Piaui, Cea…Pernambuco, Rio Grande do Norte, Bahia, Tocantins", UTCoffset: "-03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Brazil, Distrito Federal, Espirito Santo, Goias, M…iro, Rio Grande do Sul, Santa Catarina, Sao Paulo", UTCoffset: "-03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Brazil, small islands in Atlantic (Fernando de Noronha, Trindade)", UTCoffset: "-02:00", DST: "-", DSTperiodStartEnd: ""},
{country: "British Indian Ocean Territory (UK)", UTCoffset: "+06:00", DST: "-", DSTperiodStartEnd: ""},
{country: "British Virgin Islands (UK)", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Brunei", UTCoffset: "+08:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Bulgaria", UTCoffset: "+02:00", DST: "+03:00", DSTperiodStartEnd: "Last Sunday in March, 03:00 Last Sunday in October, 04:00"},
{country: "Burkina Faso", UTCoffset: "+00:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Burundi", UTCoffset: "+02:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Cabo Verde", UTCoffset: "-01:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Cambodia", UTCoffset: "+07:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Cameroon", UTCoffset: "+01:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Caribbean Netherlands (Netherlands)", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Cayman Islands (UK)", UTCoffset: "-05:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Central African Republic", UTCoffset: "+01:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Chad", UTCoffset: "+01:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Chatham Islands (New Zealand)", UTCoffset: "+12:45", DST: "+13:45", DSTperiodStartEnd: "Last Sunday in September, 02:45 1-st Sunday in April, 03:45"},
{country: "Chile, main territory", UTCoffset: "-04:00", DST: "-03:00", DSTperiodStartEnd: "2-nd Sunday in August, 00:00 2-nd Sunday in May, 00:00"},
{country: "Chile, Magallanes Region", UTCoffset: "-03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Chile, Easter Island", UTCoffset: "-06:00", DST: "-05:00", DSTperiodStartEnd: "2-nd Sunday in August, 22:00 2-nd Sunday in May, 22:00"},
{country: "China", UTCoffset: "+08:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Christmas Island (Australia)", UTCoffset: "+07:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Cocos (Keeling) Islands (Australia)", UTCoffset: "+06:30", DST: "-", DSTperiodStartEnd: ""},
{country: "Colombia", UTCoffset: "-05:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Comoros", UTCoffset: "+03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Congo, Republic of the", UTCoffset: "+01:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Congo, Dem. Rep., western part", UTCoffset: "+01:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Congo, Dem. Rep., eastern part", UTCoffset: "+02:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Cook Islands (New Zealand)", UTCoffset: "-10:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Costa Rica", UTCoffset: "-06:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Cote d'Ivoire", UTCoffset: "+00:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Croatia", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Cuba", UTCoffset: "-05:00", DST: "-04:00", DSTperiodStartEnd: "2-nd Sunday in March, 00:00 1-st Sunday in November, 01:00"},
{country: "Curacao (Netherlands)", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Cyprus", UTCoffset: "+02:00", DST: "+03:00", DSTperiodStartEnd: "Last Sunday in March, 03:00 Last Sunday in October, 04:00"},
{country: "Czechia", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Denmark", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Djibouti", UTCoffset: "+03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Dominica", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Dominican Republic", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Ecuador, main territory", UTCoffset: "-05:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Ecuador, Galapagos Province", UTCoffset: "-06:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Egypt", UTCoffset: "+02:00", DST: "-", DSTperiodStartEnd: ""},
{country: "El Salvador", UTCoffset: "-06:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Equatorial Guinea", UTCoffset: "+01:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Eritrea", UTCoffset: "+03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Estonia", UTCoffset: "+02:00", DST: "+03:00", DSTperiodStartEnd: "Last Sunday in March, 03:00 Last Sunday in October, 04:00"},
{country: "Eswatini (formerly Swaziland)", UTCoffset: "+02:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Ethiopia", UTCoffset: "+03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Falkland Islands (UK)", UTCoffset: "-03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Faroe Islands (Denmark)", UTCoffset: "+00:00", DST: "+01:00", DSTperiodStartEnd: "Last Sunday in March, 01:00 Last Sunday in October, 02:00"},
{country: "Fiji", UTCoffset: "+12:00", DST: "+13:00", DSTperiodStartEnd: "1-st Sunday in November, 02:00 3-rd Sunday in January, 03:00"},
{country: "Finland", UTCoffset: "+02:00", DST: "+03:00", DSTperiodStartEnd: "Last Sunday in March, 03:00 Last Sunday in October, 04:00"},
{country: "France", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "French Guiana (France)", UTCoffset: "-03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "French Polynesia, Tahiti Island (France)", UTCoffset: "-10:00", DST: "-", DSTperiodStartEnd: ""},
{country: "French Polynesia, Marquesas Islands (France)", UTCoffset: "-09:30", DST: "-", DSTperiodStartEnd: ""},
{country: "French Polynesia, Gambier Islands (France)", UTCoffset: "-09:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Gabon", UTCoffset: "+01:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Gambia", UTCoffset: "+00:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Georgia", UTCoffset: "+04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Germany", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Ghana", UTCoffset: "+00:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Gibraltar (UK)", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Greece", UTCoffset: "+02:00", DST: "+03:00", DSTperiodStartEnd: "Last Sunday in March, 03:00 Last Sunday in October, 04:00"},
{country: "Greenland (Denmark), most of", UTCoffset: "-03:00", DST: "-02:00", DSTperiodStartEnd: "Last Saturday in March, 22:00 Last Saturday in October, 23:00"},
{country: "Greenland (Denmark), Thule Air Base", UTCoffset: "-04:00", DST: "-03:00", DSTperiodStartEnd: "2-nd Sunday in March, 02:00 1-st Sunday in November, 03:00"},
{country: "Greenland (Denmark), Ittoqqortoormiit", UTCoffset: "-01:00", DST: "+00:00", DSTperiodStartEnd: "Last Sunday in March, 00:00 Last Sunday in October, 01:00"},
{country: "Greenland (Denmark), Danmarkshavn, Station Nord", UTCoffset: "+00:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Grenada", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Guadeloupe (France)", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Guam (USA)", UTCoffset: "+10:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Guatemala", UTCoffset: "-06:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Guernsey (UK)", UTCoffset: "+00:00", DST: "+01:00", DSTperiodStartEnd: "Last Sunday in March, 01:00 Last Sunday in October, 02:00"},
{country: "Guinea", UTCoffset: "+00:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Guinea-Bissau", UTCoffset: "+00:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Guyana", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Haiti", UTCoffset: "-05:00", DST: "-04:00", DSTperiodStartEnd: "2-nd Sunday in March, 02:00 1-st Sunday in November, 02:00"},
{country: "Honduras", UTCoffset: "-06:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Hong Kong (China)", UTCoffset: "+08:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Hungary", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Iceland", UTCoffset: "+00:00", DST: "-", DSTperiodStartEnd: ""},
{country: "India", UTCoffset: "+05:30", DST: "-", DSTperiodStartEnd: ""},
{country: "Indonesia, Sumatra Island, Java Island, West Kalimantan, Central Kalimantan", UTCoffset: "+07:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Indonesia, Sulawesi Island, Lesser Sunda Islands, …rth Kalimantan, East Kalimantan, South Kalimantan", UTCoffset: "+08:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Indonesia, Maluku Islands, Papua, West Papua", UTCoffset: "+09:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Iran", UTCoffset: "+03:30", DST: "+04:30", DSTperiodStartEnd: "March 21, 00:00 (+1 day) September 21, 00:00 (+1 day)"},
{country: "Iraq", UTCoffset: "+03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Ireland", UTCoffset: "+00:00", DST: "+01:00", DSTperiodStartEnd: "Last Sunday in March, 01:00 Last Sunday in October, 02:00"},
{country: "Isle of Man (UK)", UTCoffset: "+00:00", DST: "+01:00", DSTperiodStartEnd: "Last Sunday in March, 01:00 Last Sunday in October, 02:00"},
{country: "Israel", UTCoffset: "+02:00", DST: "+03:00", DSTperiodStartEnd: "Friday before the last Sunday in March, 02:00 Last Sunday in October, 02:00"},
{country: "Italy", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Jamaica", UTCoffset: "-05:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Japan", UTCoffset: "+09:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Jersey (UK)", UTCoffset: "+00:00", DST: "+01:00", DSTperiodStartEnd: "Last Sunday in March, 01:00 Last Sunday in October, 02:00"},
{country: "Jordan", UTCoffset: "+02:00", DST: "+03:00", DSTperiodStartEnd: "Friday after the last Thursday in March, 00:00 Last Friday in October, 01:00"},
{country: "Kazakhstan, western part", UTCoffset: "+05:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Kazakhstan, eastern part", UTCoffset: "+06:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Kenya", UTCoffset: "+03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Kerguelen Islands (France)", UTCoffset: "+05:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Kiribati, Gilbert Islands", UTCoffset: "+12:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Kiribati, Phoenix Islands", UTCoffset: "+13:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Kiribati, Line Islands", UTCoffset: "+14:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Kosovo", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Kuwait", UTCoffset: "+03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Kyrgyzstan", UTCoffset: "+06:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Laos", UTCoffset: "+07:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Latvia", UTCoffset: "+02:00", DST: "+03:00", DSTperiodStartEnd: "Last Sunday in March, 03:00 Last Sunday in October, 04:00"},
{country: "Lebanon", UTCoffset: "+02:00", DST: "+03:00", DSTperiodStartEnd: "Last Sunday in March, 00:00 Last Sunday in October, 00:00"},
{country: "Lesotho", UTCoffset: "+02:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Liberia", UTCoffset: "+00:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Libya", UTCoffset: "+02:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Liechtenstein", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Lithuania", UTCoffset: "+02:00", DST: "+03:00", DSTperiodStartEnd: "Last Sunday in March, 03:00 Last Sunday in October, 04:00"},
{country: "Luxembourg", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Macau (China)", UTCoffset: "+08:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Madagascar", UTCoffset: "+03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Malawi", UTCoffset: "+02:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Malaysia", UTCoffset: "+08:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Maldives", UTCoffset: "+05:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Mali", UTCoffset: "+00:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Malta", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Marshall Islands", UTCoffset: "+12:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Martinique (France)", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Mauritania", UTCoffset: "+00:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Mauritius", UTCoffset: "+04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Mayotte (France)", UTCoffset: "+03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Mexico, most of", UTCoffset: "-06:00", DST: "-05:00", DSTperiodStartEnd: "1-st Sunday in April, 02:00 Last Sunday in October, 02:00"},
{country: "Mexico, state of Quintana Roo", UTCoffset: "-05:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Mexico, states of Baja California Sur, Chihuahua, Nayarit, Sinaloa", UTCoffset: "-07:00", DST: "-06:00", DSTperiodStartEnd: "1-st Sunday in April, 02:00 Last Sunday in October, 02:00"},
{country: "Mexico, state of Sonora", UTCoffset: "-07:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Mexico, state of Baja California", UTCoffset: "-08:00", DST: "-07:00", DSTperiodStartEnd: "2-nd Sunday in March, 02:00 1-st Sunday in November, 02:00"},
{country: "Micronesia, states of Chuuk and Yap", UTCoffset: "+10:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Micronesia, states of Kosrae and Pohnpei", UTCoffset: "+11:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Moldova", UTCoffset: "+02:00", DST: "+03:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Monaco", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Mongolia, most of", UTCoffset: "+08:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Mongolia, provinces of Khovd, Uvs, Bayan-Olgii", UTCoffset: "+07:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Montenegro", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Montserrat (UK)", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Morocco", UTCoffset: "+01:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Mozambique", UTCoffset: "+02:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Myanmar (formerly Burma)", UTCoffset: "+06:30", DST: "-", DSTperiodStartEnd: ""},
{country: "Namibia", UTCoffset: "+02:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Nauru", UTCoffset: "+12:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Nepal", UTCoffset: "+05:45", DST: "-", DSTperiodStartEnd: ""},
{country: "Netherlands", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "New Caledonia (France)", UTCoffset: "+11:00", DST: "-", DSTperiodStartEnd: ""},
{country: "New Zealand", UTCoffset: "+12:00", DST: "+13:00", DSTperiodStartEnd: "Last Sunday in September, 02:00 1-st Sunday in April, 03:00"},
{country: "Nicaragua", UTCoffset: "-06:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Niger", UTCoffset: "+01:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Nigeria", UTCoffset: "+01:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Niue (New Zealand)", UTCoffset: "-11:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Norfolk Island (Australia)", UTCoffset: "+11:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Northern Mariana Islands (USA)", UTCoffset: "+10:00", DST: "-", DSTperiodStartEnd: ""},
{country: "North Korea", UTCoffset: "+09:00", DST: "-", DSTperiodStartEnd: ""},
{country: "North Macedonia (formerly Macedonia)", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Norway", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Oman", UTCoffset: "+04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Pakistan", UTCoffset: "+05:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Palau", UTCoffset: "+09:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Palestine", UTCoffset: "+02:00", DST: "+03:00", DSTperiodStartEnd: "Last Saturday in March, 01:00 Last Saturday in October, 01:00"},
{country: "Panama", UTCoffset: "-05:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Papua New Guinea, most of", UTCoffset: "+10:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Papua New Guinea, Bougainville Island", UTCoffset: "+11:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Paraguay", UTCoffset: "-04:00", DST: "-03:00", DSTperiodStartEnd: "1-st Sunday in October, 00:00 Last Sunday in March, 00:00"},
{country: "Peru", UTCoffset: "-05:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Philippines", UTCoffset: "+08:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Pitcairn Islands (UK)", UTCoffset: "-08:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Poland", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Portugal, main territory", UTCoffset: "+00:00", DST: "+01:00", DSTperiodStartEnd: "Last Sunday in March, 01:00 Last Sunday in October, 02:00"},
{country: "Portugal, Azores", UTCoffset: "-01:00", DST: "+00:00", DSTperiodStartEnd: "Last Sunday in March, 00:00 Last Sunday in October, 01:00"},
{country: "Puerto Rico (USA)", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Qatar", UTCoffset: "+03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Reunion (France)", UTCoffset: "+04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Romania", UTCoffset: "+02:00", DST: "+03:00", DSTperiodStartEnd: "Last Sunday in March, 03:00 Last Sunday in October, 04:00"},
{country: "Rwanda", UTCoffset: "+02:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Saba (Netherlands)", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Saint Barthelemy (France)", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Saint Helena (UK)", UTCoffset: "+00:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Saint Kitts and Nevis", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Saint Lucia", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Saint Martin (France)", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Saint Pierre and Miquelon (France)", UTCoffset: "-03:00", DST: "-02:00", DSTperiodStartEnd: "2-nd Sunday in March, 02:00 1-st Sunday in November, 02:00"},
{country: "Saint Vincent and the Grenadines", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Samoa", UTCoffset: "+13:00", DST: "+14:00", DSTperiodStartEnd: "Last Sunday in September, 03:00 1-st Sunday in April, 04:00"},
{country: "San Marino", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Sao Tome and Principe", UTCoffset: "+00:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Saudi Arabia", UTCoffset: "+03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Senegal", UTCoffset: "+00:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Serbia", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Seychelles", UTCoffset: "+04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Sierra Leone", UTCoffset: "+00:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Singapore", UTCoffset: "+08:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Sint Eustatius (Netherlands)", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Sint Maarten (Netherlands)", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Slovakia", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Slovenia", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Solomon Islands", UTCoffset: "+11:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Somalia", UTCoffset: "+03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "South Africa", UTCoffset: "+02:00", DST: "-", DSTperiodStartEnd: ""},
{country: "South Georgia Island (UK)", UTCoffset: "-02:00", DST: "-", DSTperiodStartEnd: ""},
{country: "South Korea", UTCoffset: "+09:00", DST: "-", DSTperiodStartEnd: ""},
{country: "South Sudan", UTCoffset: "+03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Spain, main territory", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Spain, Canary Islands", UTCoffset: "+00:00", DST: "+01:00", DSTperiodStartEnd: "Last Sunday in March, 01:00 Last Sunday in October, 02:00"},
{country: "Sri Lanka", UTCoffset: "+05:30", DST: "-", DSTperiodStartEnd: ""},
{country: "Sudan", UTCoffset: "+02:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Suriname", UTCoffset: "-03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Svalbard and Jan Mayen (Norway)", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Sweden", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Switzerland", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Syria", UTCoffset: "+02:00", DST: "+03:00", DSTperiodStartEnd: "Last Friday in March, 00:00 Last Friday in October, 00:00"},
{country: "Taiwan", UTCoffset: "+08:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Tajikistan", UTCoffset: "+05:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Tanzania", UTCoffset: "+03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Thailand", UTCoffset: "+07:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Timor-Leste", UTCoffset: "+09:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Togo", UTCoffset: "+00:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Tokelau (New Zealand)", UTCoffset: "+13:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Tonga", UTCoffset: "+13:00", DST: "+14:00", DSTperiodStartEnd: "1-st Sunday in November, 02:00 3-rd Sunday in January, 03:00"},
{country: "Trinidad and Tobago", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Tristan da Cunha (UK)", UTCoffset: "+00:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Tunisia", UTCoffset: "+01:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Turkey", UTCoffset: "+03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Turkmenistan", UTCoffset: "+05:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Turks and Caicos Islands (UK)", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Tuvalu", UTCoffset: "+12:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Uganda", UTCoffset: "+03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Ukraine", UTCoffset: "+02:00", DST: "+03:00", DSTperiodStartEnd: "Last Sunday in March, 03:00 Last Sunday in October, 04:00"},
{country: "United Arab Emirates", UTCoffset: "+04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "United Kingdom", UTCoffset: "+00:00", DST: "+01:00", DSTperiodStartEnd: "Last Sunday in March, 01:00 Last Sunday in October, 02:00"},
{country: "Uruguay", UTCoffset: "-03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "US Virgin Islands (USA)", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Uzbekistan", UTCoffset: "+05:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Vanuatu", UTCoffset: "+11:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Vatican City (Holy See)", UTCoffset: "+01:00", DST: "+02:00", DSTperiodStartEnd: "Last Sunday in March, 02:00 Last Sunday in October, 03:00"},
{country: "Venezuela", UTCoffset: "-04:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Vietnam", UTCoffset: "+07:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Wake Island (USA)", UTCoffset: "+12:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Wallis and Futuna (France)", UTCoffset: "+12:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Yemen", UTCoffset: "+03:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Zambia", UTCoffset: "+02:00", DST: "-", DSTperiodStartEnd: ""},
{country: "Zimbabwe", UTCoffset: "+02:00", DST: "-", DSTperiodStartEnd: ""},
]